#references (order is slightly mixed)
# https://arxiv.org/pdf/2410.11531
# https://github.com/SinketsuZao/AGENTiGraph/tree/main
# https://medium.com/preprintblog/how-to-solve-port-5000-is-in-use-by-another-program-when-debug-python-flask-code-e1733314a77e
# https://python-adv-web-apps.readthedocs.io/en/latest/flask.html
# https://www.geeksforgeeks.org/python/flask-app-routing/
# https://python-adv-web-apps.readthedocs.io/en/latest/flask3.html
# https://www.parlant.io/docs/production/custom-frontend/
# https://docs.langchain.com/oss/python/langchain/models
# https://docs.langchain.com/oss/python/langchain/streaming
# https://github.com/RManLuo/gfm-rag
# https://github.com/HKUST-KnowComp/AutoSchemaKG/tree/main
# https://arxiv.org/pdf/2201.09680
# https://blog1.neuralengineer.org/llm-moderation-classifer-openai-moderation-api-fdb124c4536a
# https://github.com/asarm/graph_chatbot
# https://gist.github.com/jvelezmagic/f3653cc2ddab1c91e86751c8b423a1b6
# https://github.com/dmitrizzle/chat-bubble
# https://github.com/Emmyme/cute-notes
# https://networkx.org/documentation/stable//reference/classes/graph.html#networkx.Graph
# https://blog.naver.com/hyunniy/223150373150
# https://platform.openai.com/docs/guides/moderation
# https://github.com/tamara-glazer/med-image-classifier
# and some potential sources that i might have missed.


# use of generative ai
# used open source code from initial html template and then used chatgpt to custom
# (created template through powerpoint and asked chatgpt to help convert to html)
# used chatgpt to revise my prompts so that it is more machine friendly and clearer
# used chatgpt (and googled) to fix and understand some bugs in code such as compatible packageversion issue, 
# clearing cache and replacing placerholder names,

# Flask app for the chatbot

from flask import Flask, render_template, request, jsonify, Response, stream_with_context
from chatbot import GirlyChatbot
import socket
import json

app = Flask(__name__)

# make the chatbot
try: 
    chatbot = GirlyChatbot()
    print("Chatbot is ready!")
except Exception as error:
    print("Error occured while initialising chatbot: " + str(error))


# home page
@app.route('/')
def index():
    """
    Render the home page of the chatbot application.

    Returns:
        str: Rendered HTML template for the chatbot interface.
    """
    return render_template('index.html')


# clear memory
@app.route('/clear', methods=['POST', 'GET'])
def clear_memory():
    """
    Clear the chatbot's conversation memory and knowledge graph.

    This endpoint resets the chatbot's state, removing all stored
    conversation history and extracted knowledge.

    Returns:
        Response: JSON response with error status and confirmation message.
    """
    result = chatbot.clear_memory()
    response = jsonify({'error': False, 'message': result})
    response.headers['Cache-Control'] = 'no-store'
    return response


# get graph data for visualisation
@app.route('/graph-data', methods=['GET'])
def graph_data():
    """
    Retrieve the knowledge graph data for visualization.

    This endpoint returns the current state of the knowledge graph,
    including all nodes (people, concepts) and edges (relationships)
    for rendering in the frontend visualization.

    Returns:
        Response: JSON response containing nodes and edges data for the graph.
    """
    data = chatbot.kg.get_graph_data()
    return jsonify({'error': False, 'data': data})


# helper function to generate SSE events
def generate_stream(message):
    """
    Generate Server-Sent Events (SSE) for streaming chat responses.

    This generator function yields SSE-formatted data for each token
    or event produced by the chatbot's streaming response.

    Args:
        message (str): The user's input message to process.

    Yields:
        str: SSE-formatted string containing JSON event data with types
             'token', 'done', 'error', or 'rejected'.
    """
    for event in chatbot.chat_stream(message):
        yield "data: " + json.dumps(event) + "\n\n"


# stream chat using SSE
@app.route('/chat-stream', methods=['POST'])
def chat_stream():
    """
    Handle chat requests with streaming responses using Server-Sent Events.

    This endpoint receives a user message via POST request and returns
    a streaming response that sends tokens as they are generated by the
    language model.

    Returns:
        Response: An SSE stream containing chat response tokens and events.
    """
    message = request.json.get('message', '').strip()
    response = Response(stream_with_context(generate_stream(message)), mimetype='text/event-stream')
    response.headers['Cache-Control'] = 'no-store'
    return response


# find a port thats not being used
def find_port():
    """
    Find an available port for the Flask application.

    Searches for an open port in the range 5000-5099 by attempting
    to bind a socket to each port sequentially.

    Returns:
        int: The first available port number found, or None if no
             ports are available in the specified range.
    """
    for port in range(5000, 5100):
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.bind(('127.0.0.1', port))
            sock.close()
            return port
        except:
            continue


# run the app
if __name__ == '__main__':
    print("Starting the app!")

    port = find_port()
    print("App available at http://127.0.0.1:" + str(port))

    app.run(debug=True, host='127.0.0.1', port=port, use_reloader=False)
